FROM python:3.8-alpine

RUN apk --update add curl  build-dependencies
RUN apk --update add --virtual python-dev build-dependencies libffi-dev openssl-dev py-pip build-base


RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -


WORKDIR /rasa

COPY ./* ./

RUN python -m pip install -U pip

RUN /bin/bash -c "source $HOME/.poetry/env && cd /rasa &&  poetry install && \
    pip3 install rasa-x --extra-index-url https://pypi.rasa.com/simple"
