FROM python:3.8-slim

RUN apt-get update && apt install -y curl

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

#reoslve gcc dependency
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc and-build-dependencies \
    && rm -rf /var/lib/apt/lists/* \
    && pip install cryptography \
    && apt-get purge -y --auto-remove gcc and-build-dependencies

WORKDIR /rasa

COPY ./* ./

RUN python -m pip install -U pip

RUN /bin/bash -c "source $HOME/.poetry/env && cd /rasa &&  poetry install && \
    pip3 install rasa-x --extra-index-url https://pypi.rasa.com/simple"
